# Hannan's Lesson 5 Notebook

In [18]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)


1) Create an array containing 4 string elements: your first name, your last name, your birth
state and your favorite color.



In [22]:
personal_info = np.array(['Rao', 'Abdul Hannan', 'Pakistan','Blue'])
personal_info

array(['Rao', 'Abdul Hannan', 'Pakistan', 'Blue'], dtype='<U12')

a.	Use a numpy function to make all elements uppercase. 

In [24]:
upper_case = np.char.upper(personal_info)
upper_case

array(['RAO', 'ABDUL HANNAN', 'PAKISTAN', 'BLUE'], dtype='<U12')

b.	Use a numpy function to count the number of times the letter “a” appears in each element of your array.

In [25]:
number_of_a = np.char.count(personal_info, 'a')
number_of_a

array([1, 2, 2, 0])

c.	Optional: Use a numpy function to find the length of each element in the array. You may need to Google this. 

In [27]:
sizes = []
for i in personal_info:
    sizes.append(len(i))
sizes

[3, 12, 8, 4]

2)	Create an array containing EVERY OTHER odd number starting with 1 and ending with (and including) 41. 

In [45]:
odd_numbers = np.arange(1, 42, 1)
odd_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41])

a.	Use numpy to find the sum and the product of the elements of this array. NOTE: This will require you to convert the elements of your array to floats using the astype method.

In [46]:
float_odd_numbers = odd_numbers.astype(float)
sum = np.sum(odd_numbers)
sum

861

In [47]:
product = np.prod(float_odd_numbers)
product

3.3452526613163803e+49

b.	Use numpy to take the natural log of each element.

In [48]:
log_array = np.log(odd_numbers)
log_array

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207])